name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "AIO FIFA 19 update"
  comment: "fifa 19 mod fc25"
  url: "https://download2388.mediafire.com/lptipsegvn7goGN40MdW4bVPOGes8yNFYQIJyOvvaAZ2KJwrh3af3hU_CEv7eib4AmEJsTOuSnrKMhP-7Hf2xAatWEw_Z9fVOb-ok5kwsU_3k_hrFUpRdiswedc4zJOlg6lzsxXsFWpCiupy3n2IxMk8RFS5mApDT1sOL6v82OnYgzTj9w/4j3mvb0cok62ej2/UPTOWN+GAMES+-+FIFA+19+PATCH+FC+25+AIO.zip"
  file_name: "AIO fifa 19 to fc25"
  piece_size: 22 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
